{% set name = "napari-sc3d-viewer" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3138b84b2ef970c392aefece1fe9e747acddca4c4d2f837325efc720da1c7062

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - python >={{ python_min }}
    - qtpy
    - sc-3d

test:
  imports:
    - napari_sc3d_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-sc3D-viewer/
  summary: A plugin to visualize 3D single cell omics
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/GuignardLab/napari-sc3D-viewer

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
