{% set name = "napari-sc3d-viewer" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-sc3D-viewer-{{ version }}.tar.gz
  sha256: 2d262621429c4f44b5d60fcc5adb0135a70bf019ecdc7fbd74f2628cdd0259ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - sc-3d

test:
  imports:
    - napari_sc3d_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GuignardLab/napari-sc3D-viewer
  summary: A plugin to visualize 3D single cell omics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
