{% set name = "napari-sc3d-viewer" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-sc3D-viewer-{{ version }}.tar.gz
  sha256: 27847ed3259691f95a2ba8c6375e91f59ba5dd300872b767251854b2cddca81e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - sc-3d

test:
  imports:
    - napari_sc3d_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GuignardLab/napari-sc3D-viewer
  summary: A plugin to visualize 3D single cell omics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
