{% set name = "napari-sc3d-viewer" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-sc3D-viewer-{{ version }}.tar.gz
  sha256: 959d4e9c67f5f0d8e094a3a6a34dc2e5cc760c9d045f3b2e4a45044f4b402c09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - python >={{ python_min }}
    - qtpy
    - sc-3d

test:
  imports:
    - napari_sc3d_viewer
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-sc3D-viewer/
  summary: A plugin to visualize 3D single cell omics
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/GuignardLab/napari-sc3D-viewer

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
